### ISSUE TITLE
[Suggestion] Swap sides

### ISSUE THREAD

**Issue by gaussandhisgun** [muhammad-ans/notification-icons#1]
This is a really cool extension, and it managed to do something that I personally thought was impossible on Gnome. But there's one thing that I feel can be improved.

My setup is configured to look mostly like Android, and this extension does a great job at doing that, except the notification icons are displayed to the left of the clock, while in actual Android they are to the right. Maybe a toggle can be implemented to change the side of the icons? Thanks.

**Comment by muhammad-ans** [comment]
Will look into it.

**Comment by muhammad-ans** [comment]
completed in https://github.com/muhammad-ans/notification-icons/commit/2a4b2cb174f301693548756e7ee7b0433a7f7070
