### ISSUE TITLE
[Suggestion] Symbolic Icons

### ISSUE THREAD

**Issue by gaussandhisgun** [muhammad-ans/notification-icons#2]
Gnome Shell is known for its semi-minimalistic design. So, seeing a colored Firefox icon right next to a monochrome bar feels... weird. Maybe, its possible to make the extension use symbolic icons if they are available?

![изображение](https://github.com/muhammad-ans/notification-icons/assets/63512006/e9aae0ac-3f7b-4533-9ad2-7b8015fbe4f4)

**Comment by muhammad-ans** [comment]
Icons shown will be symbolic/monochrome.
